# exp setting
exp_name: 'fmae_av2_val_finetune' # name that will be used in wandb
ckpt_path: ./unitraj_ckpt/fmae/fixed_model_forecast_finetune.ckpt #./models/emp/pretrained_weights/empm.ckpt # checkpoint path, used for evaluation
seed: 42 # random seed
debug: False # debug mode, will use cpu only
devices: [ 0 ] # gpu ids

# data related
load_num_workers: 4 # number of workers for loading data
train_data_path: [ "data_samples/vod_train" ] # list of paths to the training data
val_data_path: [ "data_samples/av2_val/val_test_new" ] # list of paths to the validation data
cache_path: "./cache"
max_data_num: [ null ] # maximum number of data for each training dataset, null means all data
starting_frame: [ 0 ] # history trajectory starts at this frame for each training dataset
past_len: 50 #50 # history trajectory length for UniTraj, 2.1s -> set to 5s for forecastMAE and EMP as they use 5s history
future_len: 60 # future trajectory length, 6s
object_type: [ 'VEHICLE' , 'PEDESTRIAN', 'CYCLIST'] # object types included in the training set
line_type: [ 'lane'] #only lane for fmae and emp #,'stop_sign','road_edge','road_line','crosswalk','speed_bump' ] # line type to be considered in the input
masked_attributes: [ 'z_axis', 'size' ] # attributes to be masked in the input
trajectory_sample_interval: 1 # sample interval for the trajectory
only_train_on_ego: False # only train on AV
center_offset_of_map: [ 30.0, 0.0 ] # center offset of the map
use_cache: False # use cache for data loading
overwrite_cache: True # overwrite existing cache
store_data_in_memory: False # store data in memory
remove_outliers: True # remove outliers in the data

# official evaluation
nuscenes_dataroot: '/mnt/nas3_rcp_enac_u0900_vita_scratch/datasets/Prediction-Dataset/nuscenes/nuscenes_root'
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool
eval_argoverse2: False # whether to evaluate with argoverse evaluation tool

defaults:
  - method: forecast